# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import qkd_grpc_cascade_pb2 as qkd__grpc__cascade__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in qkd_grpc_cascade_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class CascadeServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.AskParities = channel.unary_unary(
                '/qkd.CascadeService/AskParities',
                request_serializer=qkd__grpc__cascade__pb2.ParityRequest.SerializeToString,
                response_deserializer=qkd__grpc__cascade__pb2.ParityResponse.FromString,
                _registered_method=True)
        self.StartReconciliation = channel.unary_unary(
                '/qkd.CascadeService/StartReconciliation',
                request_serializer=qkd__grpc__cascade__pb2.StartRequest.SerializeToString,
                response_deserializer=qkd__grpc__cascade__pb2.Empty.FromString,
                _registered_method=True)
        self.EndReconciliation = channel.unary_unary(
                '/qkd.CascadeService/EndReconciliation',
                request_serializer=qkd__grpc__cascade__pb2.EndRequest.SerializeToString,
                response_deserializer=qkd__grpc__cascade__pb2.Empty.FromString,
                _registered_method=True)
        self.ShareParameterEstimationIndexes = channel.unary_unary(
                '/qkd.CascadeService/ShareParameterEstimationIndexes',
                request_serializer=qkd__grpc__cascade__pb2.PEIndexRequest.SerializeToString,
                response_deserializer=qkd__grpc__cascade__pb2.Empty.FromString,
                _registered_method=True)


class CascadeServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def AskParities(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StartReconciliation(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EndReconciliation(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ShareParameterEstimationIndexes(self, request, context):
        """NOUVEAU: Bob envoie les index à révéler pour PE
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CascadeServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'AskParities': grpc.unary_unary_rpc_method_handler(
                    servicer.AskParities,
                    request_deserializer=qkd__grpc__cascade__pb2.ParityRequest.FromString,
                    response_serializer=qkd__grpc__cascade__pb2.ParityResponse.SerializeToString,
            ),
            'StartReconciliation': grpc.unary_unary_rpc_method_handler(
                    servicer.StartReconciliation,
                    request_deserializer=qkd__grpc__cascade__pb2.StartRequest.FromString,
                    response_serializer=qkd__grpc__cascade__pb2.Empty.SerializeToString,
            ),
            'EndReconciliation': grpc.unary_unary_rpc_method_handler(
                    servicer.EndReconciliation,
                    request_deserializer=qkd__grpc__cascade__pb2.EndRequest.FromString,
                    response_serializer=qkd__grpc__cascade__pb2.Empty.SerializeToString,
            ),
            'ShareParameterEstimationIndexes': grpc.unary_unary_rpc_method_handler(
                    servicer.ShareParameterEstimationIndexes,
                    request_deserializer=qkd__grpc__cascade__pb2.PEIndexRequest.FromString,
                    response_serializer=qkd__grpc__cascade__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'qkd.CascadeService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('qkd.CascadeService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class CascadeService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def AskParities(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/qkd.CascadeService/AskParities',
            qkd__grpc__cascade__pb2.ParityRequest.SerializeToString,
            qkd__grpc__cascade__pb2.ParityResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StartReconciliation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/qkd.CascadeService/StartReconciliation',
            qkd__grpc__cascade__pb2.StartRequest.SerializeToString,
            qkd__grpc__cascade__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def EndReconciliation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/qkd.CascadeService/EndReconciliation',
            qkd__grpc__cascade__pb2.EndRequest.SerializeToString,
            qkd__grpc__cascade__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ShareParameterEstimationIndexes(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/qkd.CascadeService/ShareParameterEstimationIndexes',
            qkd__grpc__cascade__pb2.PEIndexRequest.SerializeToString,
            qkd__grpc__cascade__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
